services:
  mcp_server_lab:
    image: ghcr.io/abdallahsaber065/mcp-server-lab:latest
    container_name: mcp_server_lab
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:8011:8000"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
