/**
 * Catalog Lookup Service (platform/src/services/catalogService.ts)
 * Provides synchronous and cached unit/property lookup for in-chat rich component rendering.
 */

import { ShowcaseUnit } from '../components/chat/ChatUnitsShowcase';

export const STATIC_CATALOG_UNITS: ShowcaseUnit[] = [
  {
    unit_id: 101,
    unit_number: '101-Penthouse',
    title: 'The Nile Sky Penthouse Suite',
    property_id: 1,
    property_name: 'Nile Plaza Luxury Residences',
    city: 'Cairo',
    neighborhood: 'Garden City Waterfront',
    bedrooms: 3,
    bathrooms: 3.5,
    square_feet: 280.0,
    monthly_rent: 45000.0,
    status: 'occupied',
    image_url: '/images/properties/nile_tower_penthouse.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=2vyX8P3NZK8',
    is_high_value: true
  },
  {
    unit_id: 102,
    unit_number: '102-Executive',
    title: 'Garden City Horizon Suite',
    property_id: 1,
    property_name: 'Nile Plaza Luxury Residences',
    city: 'Cairo',
    neighborhood: 'Garden City Waterfront',
    bedrooms: 2,
    bathrooms: 2.0,
    square_feet: 165.0,
    monthly_rent: 28000.0,
    status: 'available',
    image_url: '/images/properties/nile_tower_bed.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=KUZJUtbxYY9',
    is_high_value: false
  },
  {
    unit_id: 103,
    unit_number: '103-Diplomatic',
    title: 'Nile Diplomatic Grand Suite',
    property_id: 1,
    property_name: 'Nile Plaza Luxury Residences',
    city: 'Cairo',
    neighborhood: 'Garden City Waterfront',
    bedrooms: 4,
    bathrooms: 4.5,
    square_feet: 340.0,
    monthly_rent: 55000.0,
    status: 'occupied',
    image_url: '/images/properties/luxury_bath.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=2vyX8P3NZK8',
    is_high_value: true
  },
  {
    unit_id: 201,
    unit_number: '201-Heritage',
    title: 'Historic Zamalek Belle Époque Flat',
    property_id: 2,
    property_name: 'Zamalek Royal Heritage Suites',
    city: 'Cairo',
    neighborhood: 'Zamalek Diplomatic District',
    bedrooms: 3,
    bathrooms: 2.5,
    square_feet: 210.0,
    monthly_rent: 32000.0,
    status: 'occupied',
    image_url: '/images/properties/zamalek_ext.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=GmrLYzFCBG8',
    is_high_value: false
  },
  {
    unit_id: 202,
    unit_number: '202-Courtyard',
    title: 'Zamalek Garden Courtyard Residence',
    property_id: 2,
    property_name: 'Zamalek Royal Heritage Suites',
    city: 'Cairo',
    neighborhood: 'Zamalek Diplomatic District',
    bedrooms: 2,
    bathrooms: 2.0,
    square_feet: 150.0,
    monthly_rent: 26000.0,
    status: 'available',
    image_url: '/images/properties/zamalek_living.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=pDwJPTkz7y2',
    is_high_value: false
  },
  {
    unit_id: 301,
    unit_number: 'OF-301',
    title: 'Grade-A Corporate Headquarters Floor',
    property_id: 3,
    property_name: 'Cornerstone Financial & Tech Park',
    city: 'New Cairo',
    neighborhood: 'Fifth Settlement Financial Hub',
    bedrooms: 0,
    bathrooms: 4.0,
    square_feet: 550.0,
    monthly_rent: 75000.0,
    status: 'occupied',
    image_url: '/images/properties/new_cairo_ext.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=xFCkwb48ZnZ',
    is_high_value: true
  },
  {
    unit_id: 302,
    unit_number: 'OF-302',
    title: 'Tech Incubator & Executive Suite',
    property_id: 3,
    property_name: 'Cornerstone Financial & Tech Park',
    city: 'New Cairo',
    neighborhood: 'Fifth Settlement Financial Hub',
    bedrooms: 0,
    bathrooms: 2.0,
    square_feet: 280.0,
    monthly_rent: 48000.0,
    status: 'available',
    image_url: '/images/properties/new_cairo_foyer.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=xFCkwb48ZnZ',
    is_high_value: true
  },
  {
    unit_id: 401,
    unit_number: '401-PyramidView',
    title: 'Panoramic Pyramids Sky Residence',
    property_id: 4,
    property_name: 'Giza Pyramids View Residences',
    city: 'Giza',
    neighborhood: 'Dokki Grand View',
    bedrooms: 3,
    bathrooms: 3.0,
    square_feet: 230.0,
    monthly_rent: 38000.0,
    status: 'occupied',
    image_url: '/images/properties/giza_ext.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=bD5PtbhxXmV',
    is_high_value: false
  },
  {
    unit_id: 402,
    unit_number: '402-DokkiTerrace',
    title: 'Dokki Executive Skyline Penthouse',
    property_id: 4,
    property_name: 'Giza Pyramids View Residences',
    city: 'Giza',
    neighborhood: 'Dokki Grand View',
    bedrooms: 3,
    bathrooms: 3.5,
    square_feet: 290.0,
    monthly_rent: 46000.0,
    status: 'available',
    image_url: '/images/properties/giza_lounge.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=KUZJUtbxYY9',
    is_high_value: true
  },
  {
    unit_id: 501,
    unit_number: '501-Seafront',
    title: 'Mediterranean Seafront Grand Villa',
    property_id: 5,
    property_name: 'Alexandria Mediterranean Riviera',
    city: 'Alexandria',
    neighborhood: 'Kafr Abdou Royal Enclave',
    bedrooms: 4,
    bathrooms: 4.0,
    square_feet: 380.0,
    monthly_rent: 62000.0,
    status: 'occupied',
    image_url: '/images/properties/alexandria_ext.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=PkugSohfGeH',
    is_high_value: true
  },
  {
    unit_id: 502,
    unit_number: '502-AlexPenthouse',
    title: 'Alexandria Corniche Horizon Penthouse',
    property_id: 5,
    property_name: 'Alexandria Mediterranean Riviera',
    city: 'Alexandria',
    neighborhood: 'Kafr Abdou Royal Enclave',
    bedrooms: 3,
    bathrooms: 3.0,
    square_feet: 260.0,
    monthly_rent: 39000.0,
    status: 'available',
    image_url: '/images/properties/alexandria_balcony.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=ekiSqx6SV5r',
    is_high_value: true
  },
  {
    unit_id: 601,
    unit_number: '601-LagoonVilla',
    title: 'El Gouna Superyacht Lagoon Villa',
    property_id: 6,
    property_name: 'Red Sea El Gouna Marina Haven',
    city: 'Hurghada',
    neighborhood: 'Abu Tig Marina Lagoon',
    bedrooms: 3,
    bathrooms: 3.5,
    square_feet: 310.0,
    monthly_rent: 58000.0,
    status: 'available',
    image_url: '/images/properties/rooftop_pool.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=E3sXUgQazs7',
    is_high_value: true
  },
  {
    unit_id: 602,
    unit_number: '602-MarinaSuite',
    title: 'Abu Tig Marina Executive Waterside Suite',
    property_id: 6,
    property_name: 'Red Sea El Gouna Marina Haven',
    city: 'Hurghada',
    neighborhood: 'Abu Tig Marina Lagoon',
    bedrooms: 2,
    bathrooms: 2.0,
    square_feet: 175.0,
    monthly_rent: 34000.0,
    status: 'available',
    image_url: '/images/properties/alexandria_suite.jpg',
    virtual_tour_url: 'https://my.matterport.com/show/?m=TfQ5GK87d2D',
    is_high_value: false
  }
];

export function resolveUnitsByIds(ids: (number | string)[]): ShowcaseUnit[] {
  const numIds = ids.map((id) => Number(id));
  return STATIC_CATALOG_UNITS.filter((u) => u.unit_id && numIds.includes(u.unit_id));
}
